# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZLYZhiHuDaily' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'SnapKit', '~> 3.1.2'
    pod 'CocoaLumberjack/Swift'
    pod 'SwiftyJSON', '~> 3.1.3'
    pod 'Alamofire', '~> 4.0'

  target 'ZLYZhiHuDailyTests' do
    inherit! :search_paths
  end

  target 'ZLYZhiHuDailyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
